import animationData from '@/animations/animation.json'
import failed from '@/animations/failed.json'
import successful from '@/animations/successful.json'
import { Header } from '@/components/Header/Header'
import { fetchOrderStatus_f } from '@/lib/api'
import { useEffect, useState } from 'react'
import Lottie from 'react-lottie'
import { useParams } from 'react-router-dom'

// Generated by https://quicktype.io

export interface OrderStatus {
  id: number
  product_type: string
  order_id: string
  price: string
  description: string
  status: 'pending' | 'complete' | 'failed'
}

export default function OrderStatus() {
  const orderId = useParams().order_id

  const [orderStatus, setOrderStatus] = useState<OrderStatus | null>(null)

  async function loadStatus() {
    setOrderStatus(null)
    const res = await fetchOrderStatus_f(orderId as string)
    console.log(res.data)
    const data = res.data.data as OrderStatus
    if (!res.status) return
    setOrderStatus(data)
  }

  useEffect(() => {
    loadStatus()
  }, [])

  return (
    <>
      <Header>Verifying payment</Header>
      <div>
        <div className='flex w-full flex-col items-center justify-center pt-10'>
          {!orderStatus || orderStatus.status === 'pending' ? (
            <>
              <Lottie
                options={{
                  loop: true,
                  autoplay: true,
                  animationData: animationData,
                }}
                height={200}
                width={200}
              />
              <p className='mt-5 animate-pulse text-sm'>Verifying Payment...</p>
            </>
          ) : orderStatus.status === 'failed' ? (
            <>
              <Lottie
                options={{
                  loop: false,
                  autoplay: true,
                  animationData: failed,
                }}
                width={300}
                height={200}
              />
              <p className='mt-5 text-sm'>Payment Failed</p>
            </>
          ) : (
            <>
              <Lottie
                options={{
                  loop: false,
                  autoplay: true,
                  animationData: successful,
                }}
                width={300}
                height={200}
              />
              <p className='mt-5 text-sm'>Payment Successful</p>
            </>
          )}

          <p className='text-xs opacity-70'>(Order ID: {orderId})</p>
        </div>
        <div className='p-5'>
          <div className={`mt-10 flex-col justify-center ${orderStatus?.status === 'complete' ? 'flex' : 'hidden'}`}>
            <div className='w-full rounded-xl bg-white/5 px-5 py-5'>
              {/*Details*/}
              <div className='flex flex-col gap-2'>
                <div className='flex justify-between'>
                  <p className='text-sm'>Product</p>
                  <p className='text-sm'>{orderStatus?.product_type}</p>
                </div>
                <div className='flex justify-between'>
                  <p className='text-sm'>Order ID</p>
                  <p className='text-sm'>{orderStatus?.order_id}</p>
                </div>
                <div className='flex justify-between'>
                  <p className='text-sm'>Price</p>
                  <p className='text-sm'>${orderStatus?.price}</p>
                </div>
                <div className='flex justify-between'>
                  <p className='text-sm'>Description</p>
                  <p className='text-sm'>{orderStatus?.description}</p>
                </div>
              </div>
            </div>
            <p className='mt-10 text-center text-xs opacity-70'>
              Now go back to the app or re-open the app if you have to. You should get the purchased product.
            </p>
          </div>
        </div>
      </div>
    </>
  )
}
