// Generated by https://quicktype.io

export interface CreatorProfileT {
  first_name: string
  last_name: string
  channel_name: string
  channel_banner: string
  channel_logo: string
  is_followed: boolean
  follow_counts: number
  videos_counts: number
  playlist_count: number
  videosOrLives: VideosOrLives
}

export interface VideosOrLives {
  current_page: number
  data: VideosOrLive[]
  first_page_url: string
  from: number
  last_page: number
  last_page_url: string
  links: Link[]
  next_page_url: null
  path: string
  per_page: number
  prev_page_url: string
  to: number
  total: number
}

export interface VideosOrLive {
  id: number
  title: string
  thumbnail: string
  video_loc: string
  video_type: string
  views: number
  video_duration: string
}

export interface Link {
  url: null | string
  label: string
  active: boolean
}
