import ls from '../../lib/util'

// Generated by https://quicktype.io

export interface UserProfile {
  status: boolean
  data: Data
  subscription_status: string
  message: string
}

interface Data {
  id: number
  name: string
  country_code: string
  phone: string
  email: string
  profile_pic: string
  coins: number
  created_at: string
  updated_at: string
}
export function getProfileInfoLs(): UserProfile {
  return JSON.parse(ls.get('userProfile') || 'null')
}

export function setProfileInfoLs(data: UserProfile): void {
  ls.set('userProfile', JSON.stringify(data))
}
